### ISSUE TITLE
how I get some doc about this project? 

### ISSUE THREAD

**Issue by jhonylucas74** [slap-editor/editor-widget#109]
I want to do a simple editor for my personal project and some docs will be so good to get started with this widget.

**Comment by dbkaplun** [comment]
Hi @jhonylucas74,

There is an example usage, available in the README [here](https://github.com/slap-editor/editor-widget/blob/master/README.md#example). That should be all you need to get it running. If you have any issues, feel free to join us in [#slap on Freenode](http://webchat.freenode.net/?channels=slap). Someone may not be there all the time, but you'll get a response within a day at worst.

Hope this helps!
