### ISSUE TITLE
How do I use editor-widget?

### ISSUE THREAD

**Issue by derhuerst** [slap-editor/editor-widget#148]
I want to create a code playground, which shows the results of every expression in the code right next to it.

For this, I created [`inspect-code`](https://github.com/derhuerst/inspect-code), which gives me the data. Now, using `editor-widget`, I want to display an editor and show there results inline.

**Comment by dbkaplun** [comment]
Hi @derhuerst,

Are you able to get the example running? With an editor-widget instance, you should be able to call `editor.textBuf.setText("hello world")` to get what you want if I understand correctly.

**Comment by derhuerst** [comment]
That worked for me. But I want to display something that is not in the text buffer. (Like hints in an IDE)

**Comment by dbkaplun** [comment]
@derhuerst you should be able to render blessed components on top of the widget. You may have to mess around with `moveToFront/Back` in order to achieve your goals. Closing

**Comment by derhuerst** [comment]
My question was not how to render it using blessed. I recognize that you may not have a lot a time for this project. But `editor-widget` and `slap` in general don't emit a friendly mood.

How do I modify the "screen buffer" (it's the one being rendered, right?) without modifying the text buffer? I want to show something next to a line but want it not to be part of the editable text.

**Comment by derhuerst** [comment]
bump.

**Comment by dbkaplun** [comment]
@derhuerst I think that if you reread https://github.com/slap-editor/editor-widget/issues/148#issuecomment-240181007 you will find your answer. Or is there something you were trying to do besides modifying the screen buffer without modifying the text buffer?

**Comment by derhuerst** [comment]
At least reading https://github.com/slap-editor/editor-widget/issues/148#issuecomment-240181007 doesn't _sound_ as if it was an answer at all. Even after having read this, I have no idea how I would do this.

**Comment by dbkaplun** [comment]
@derhuerst blessed is very similar to HTML in that there are components (akin to HTML tags) which are rectangular and can layer on top of one another. editor-widget is one of those components. You can get what you want by using another component like blessed's built-in Box and layering it on top of an editor-widget for e.g. an autocompletion menu, or code hints. Does that make sense?

**Comment by derhuerst** [comment]
That makes a lot of sense. Thanks!

**Comment by dbkaplun** [comment]
No worries @derhuerst! Feel free to open another ticket if you're still having trouble.

**Comment by derhuerst** [comment]
I created an editor using `editor-widget`. Then I created a box, but the editor below is not shown. How do I make the overlaying box transparent?

``` js
'use strict'

const blessed = require('blessed')
const Editor = require('editor-widget')

const screen = blessed.screen({smartCSR: true})

const editor = new Editor({
    parent: screen,
    top: 0, left: 0,
    width: '100%', height: '100%',
    gutter: {width: 0, hidden: true}
})
editor.language('js')
editor.textBuf.setText('Hello World!')

screen.key(['escape', 'C-c'], (ch, key) => process.exit(0))

const box = blessed.box({
    parent: editor,
    content: '                      Hello {bold}world{/bold}!',
    style: {}
})
screen.append(box)
```

**Comment by cancerberoSgx** [comment]
@derhuerst your problem is the box, you are putting it as child of editor. Deleting the last two statements and adding `screen.render()` at the button should do it.
