### ISSUE TITLE
how to show markers on top of editor-widget

### ISSUE THREAD

**Issue by derhuerst** [slap-editor/editor-widget#156]
crosspost from https://github.com/slap-editor/editor-widget/issues/148

I created an editor using `editor-widget`. Then I created a box, but the editor below is not shown. How do I make the overlaying box transparent?

``` js
'use strict'

const blessed = require('blessed')
const Editor = require('editor-widget')

const screen = blessed.screen({smartCSR: true})

const editor = new Editor({
    parent: screen,
    top: 0, left: 0,
    width: '100%', height: '100%',
    gutter: {width: 0, hidden: true}
})
editor.language('js')
editor.textBuf.setText('Hello World!')

screen.key(['escape', 'C-c'], (ch, key) => process.exit(0))

const box = blessed.box({
    parent: editor,
    content: '                      Hello {bold}world{/bold}!',
    style: {}
})
screen.append(box)
```

**Comment by derhuerst** [comment]
bump :)

**Comment by dbkaplun** [comment]
@derhuerst you need to give the box a width and height or blessed won't know how big to make it. You may also want to make a parent box and add the box and editor to it, rather than adding the box to the editor directly, which is intended to be a leaf node component. Please join us in [#slap on Freenode](http://webchat.freenode.net/?channels=slap) if you are still having trouble.

**Comment by dbkaplun** [comment]
I mean you are welcome to open more issues but you are welcome to join the IRC channel as well. 👍

**Comment by derhuerst** [comment]
Check this out!

[![asciicast](https://asciinema.org/a/86588.png)](https://github.com/derhuerst/js-playgrounds)

**Comment by dbkaplun** [comment]
This is amazing! @derhuerst would you mind if I linked to your project on the editor-widget README? Great work!

**Comment by derhuerst** [comment]
I don't mind!

**Comment by dbkaplun** [comment]
@derhuerst I've added it to the editor-widget README [here](https://github.com/slap-editor/editor-widget/blob/master/README.md#in-use). Can't wait to see the completed product!
